### ISSUE TITLE
Please update main net branch dependencies 

### ISSUE THREAD

**Issue by AdamZhong98** [drift-labs/keeper-bots-v2#130]
[2024-02-02T15:33:02.976Z] error: User for 85giG7tjhA1LECHPRBEZrHvkGFy39z3YmD9En8AtHmRF does not exist (subAccountId: 0)
[2024-02-02T15:33:02.976Z] info: Creating User for 85giG7tjhA1LECHPRBEZrHvkGFy39z3YmD9En8AtHmRF
SendTransactionError: failed to send transaction: Transaction simulation failed: This transaction has already been processed
    at Connection.sendEncodedTransaction (/Users/adamzhong/keeper-bots-v2/node_modules/@solana/web3.js/src/connection.ts:5922:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/Users/adamzhong/keeper-bots-v2/node_modules/@solana/web3.js/src/connection.ts:5881:20) {
  logs: []
}
/Users/adamzhong/keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/baseTxSender.js:181
        throw new Error(`Transaction was not confirmed in 30 seconds. It is unknown if it succeeded or failed. Check signature ${signature} using the Solana Explorer or CLI tools.`);
              ^
Error: Transaction was not confirmed in 30 seconds. It is unknown if it succeeded or failed. Check signature ccqYCNpbd4CiYgrQhU5HendCgsugBzWhgJJbd6tKoWdf4jGHsyi1RKHN1JuHe64GEqnm9Sfcp4ihNLYNYguvwdX using the Solana Explorer or CLI tools.
    at RetryTxSender.confirmTransactionPolling (/Users/adamzhong/keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/baseTxSender.js:181:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryTxSender.confirmTransaction (/Users/adamzhong/keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/baseTxSender.js:189:20)
    at async RetryTxSender.sendRawTransaction (/Users/adamzhong/keeper-bots-v2/node_modules/@drift-labs/sdk/lib/tx/retryTxSender.js:64:28)
    at async DriftClient.initializeUserAccount (/Users/adamzhong/keeper-bots-v2/node_modules/@drift-labs/sdk/lib/driftClient.js:439:27)
    at async checkUserExists (/Users/adamzhong/keeper-bots-v2/src/index.ts:944:20)
    at async runBot (/Users/adamzhong/keeper-bots-v2/src/index.ts:781:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wphan** [comment]
this error happens when the network is congested or your RPC node falls behind and fails to confirm the transaction. It looks like you were trying to initialize a new user, were you able to do that?
