### ISSUE TITLE
Filler Bot unable to submit transactions

### ISSUE THREAD

**Issue by liuyong5653** [drift-labs/keeper-bots-v2#137]
During the process of running the keeper bot (command: yarn start --filler --trigger --config-file example.config.yaml), it always reports the following error and transactions have not been successfully submitted.
————————————————————————————————————————————————————————
[2024-02-21T02:21:19.474Z] info: slotSubscriber slot: 249460315, userMap slot: 249460344
[2024-02-21T02:21:19.475Z] info: including taker AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d-35534 (fillTxId: 678)
[2024-02-21T02:21:19.475Z] info: Filling perp node 1 (fillTxId: 678)
taker on market 11: AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d-35536 short 0/1067 @ 0 (orderType: oracle)
makers:
  vAMM
[2024-02-21T02:21:19.475Z] info: slotSubscriber slot: 249460315, userMap slot: 249460344
[2024-02-21T02:21:19.476Z] info: including taker AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d-35536 (fillTxId: 678)
[2024-02-21T02:21:19.476Z] info: sending tx, 26 unique accounts, total ix: 2, calcd tx size: 1024, took 2ms (fillTxId: 678)
Error loading priority fee solana: Unexpected token 'j', "json metho"... is not valid JSON
SyntaxError: Unexpected token 'j', "json metho"... is not valid JSON
    at JSON.parse (<anonymous>)
    at ClientBrowser._parseResponse (/Users/yong/Desktop/project/keeper-bots-v2/node_modules/jayson/lib/client/browser/index.js:131:21)
    at /Users/yong/Desktop/project/keeper-bots-v2/node_modules/jayson/lib/client/browser/index.js:103:10
    at ClientBrowser.callServer (/Users/yong/Desktop/project/keeper-bots-v2/node_modules/@solana/web3.js/lib/index.cjs.js:6472:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Simulated tx took: 262ms
[2024-02-21T02:21:20.299Z] info: tryBulkFillPerpNodes estimated CUs: 29922 (fillTxId: 678)
[2024-02-21T02:21:20.299Z] error: simError: {"InstructionError":[4,{"Custom":6239}]} (fillTxId: 678)
[2024-02-21T02:21:20.299Z] info: Processing tx log for assoc node 0
taker on market 11: AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d-35534 short 0/1067 @ 0 (orderType: oracle)
makers:
  vAMM
[2024-02-21T02:21:20.299Z] error: assoc node (ixIdx: 0): AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d, 35534; does not exist (filled by someone else); Program log: Order does not exist 35534
[2024-02-21T02:21:20.299Z] info: Processing tx log for assoc node 1
taker on market 11: AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d-35536 short 0/1067 @ 0 (orderType: oracle)
makers:
  vAMM
[2024-02-21T02:21:20.299Z] error: assoc node (ixIdx: 1): AMDsLg6HPmkQRUBwhYMCpVoNc17tJEJmjgNpa3srWc4d, 35536; does not exist (filled by someone else); Program log: Order does not exist 35536
——————————————————————————————————————————————————

I increased maxPriorityFeeMicroLamports from 10000 to 20000 or even higher, but still couldn't submit transactions. Is it due to my computing speed, network issues, or low fee configuration?

**Comment by wphan** [comment]
this can happen if the RPC you are using is down or out of credits

**Comment by liuyong5653** [comment]
> this can happen if the RPC you are using is down or out of credits

out of credits? How to check credits?"

**Comment by wphan** [comment]
you cannot use the RPC in example.config.yaml, will remove it. Need to find your own RPC https://solana.com/rpc
